### ISSUE TITLE
How to build a semla object without h5 file？

### ISSUE THREAD

**Issue by Cambyses-Chen** [ludvigla/semla#8]
Dear authors of semla.
Thank you for developing such an excellent spatial transcriptome analysis software as semla.
I only have filtered_count_matrices folder with 3 files, no h5 files.
How should I construct a semla object？
I have other files "aligned_fiducials.jpg", "detected_tissue_image.jpg", "scalefactors_json.json", "tissue_hires_image.png", "tissue_positions_list.csv".
Thank you for the help.

**Comment by ludvigla** [comment]
Hi!

I just pushed a minor fix to make it possible to load the filtered_count_matrices folder instead of the h5 files.

When you construct the `infoTable` for `ReadVisiumData` you can just place the filtered_count_matrices folder paths in the `samples` column and it should work now.

Just make sure to install the latest dev version of semla.

Cheers,
Ludvig

**Comment by Cambyses-Chen** [comment]
> Hi!
> 
> I just pushed a minor fix to make it possible to load the filtered_count_matrices folder instead of the h5 files.
> 
> When you construct the `infoTable` for `ReadVisiumData` you can just place the filtered_count_matrices folder paths in the `samples` column and it should work now.
> 
> Just make sure to install the latest dev version of semla.
> 
> Cheers, Ludvig
Thank you so much！I will try the method you provide.

**Comment by Cambyses-Chen** [comment]
This problem has been solved, thanks to Ludvig.
